<x-app-layout>
    <div class="max-w-4xl mx-auto py-10 px-4 sm:px-6 lg:px-8">
        <div class="bg-white shadow-xl rounded-lg p-6 sm:p-8">
            
            <div class="border-b border-gray-200 pb-4 mb-6 flex justify-between items-center">
                <h2 class="text-2xl font-bold text-gray-800">University Complaint Portal</h2>
                <span class="px-3 py-1 bg-indigo-100 text-indigo-800 text-xs font-semibold rounded-full">Student Ticket Form</span>
            </div>

            @if(session('success'))
                <div class="mb-4 bg-green-50 border-l-4 border-green-400 p-4 text-green-700 text-sm">
                    {{ session('success') }}
                </div>
            @endif

            @if ($errors->any())
                <div class="mb-4 bg-red-50 border-l-4 border-red-400 p-4 text-red-700 text-sm">
                    <ul class="list-disc pl-5 space-y-1">
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <form action="{{ route('complaints.store') }}" method="POST">
                @csrf

                <!-- Basic Details Grid -->
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-6 mb-6">
                    
                    <!-- Ticket No (Auto) -->
                    <div>
                        <label class="block text-sm font-medium text-gray-700">Ticket No</label>
                        <input type="text" disabled value="TCK-AUTOGENERATED" 
                            class="mt-1 block w-full rounded-md border-gray-300 bg-gray-100 text-gray-500 shadow-sm cursor-not-allowed">
                    </div>

                    <!-- Student Grn / Roll No -->
                    <div>
                        <label class="block text-sm font-medium text-gray-700">Student Gr No / Roll No</label>
                        <input type="text" value="{{ optional($user->studentProfile)->gr_number ?? optional($user->studentProfile)->roll_number ?? 'N/A' }}" readonly 
                            class="mt-1 block w-full rounded-md border-gray-300 bg-gray-100 text-gray-600 shadow-sm">
                    </div>

                    <!-- Name -->
                    <div>
                        <label class="block text-sm font-medium text-gray-700">Full Name</label>
                        <input type="text" value="{{ $user->name }}" readonly 
                            class="mt-1 block w-full rounded-md border-gray-300 bg-gray-100 text-gray-600 shadow-sm">
                    </div>

                    <!-- Mobile No (Auto Captured) -->
                    <div>
                        <label class="block text-sm font-medium text-gray-700">Mobile No (Auto Captured)</label>
                        <input type="text" value="{{ optional($user->studentProfile)->phone_number ?? 'N/A' }}" readonly 
                            class="mt-1 block w-full rounded-md border-gray-300 bg-gray-100 text-gray-600 shadow-sm">
                    </div>

                    <!-- Email ID -->
                    <div>
                        <label class="block text-sm font-medium text-gray-700">Email ID</label>
                        <input type="email" value="{{ $user->email }}" readonly 
                            class="mt-1 block w-full rounded-md border-gray-300 bg-gray-100 text-gray-600 shadow-sm">
                    </div>

                    <!-- Date of Complaint (Auto) -->
                    <div>
                        <label class="block text-sm font-medium text-gray-700">Date of Complaint</label>
                        <input type="text" value="{{ date('d-M-Y H:i') }}" readonly 
                            class="mt-1 block w-full rounded-md border-gray-300 bg-gray-100 text-gray-600 shadow-sm">
                    </div>

                    <!-- Conditional Hosteller Details (If applicable based on profile) -->
                    @if(optional($user->studentProfile)->student_type === 'Hostel' || optional($user->studentProfile)->hostel_name)
                    <div>
                        <label class="block text-sm font-medium text-gray-700">Hostel Name</label>
                        <input type="text" value="{{ optional($user->studentProfile)->hostel_name ?? 'Hostel Student' }}" readonly 
                            class="mt-1 block w-full rounded-md border-gray-300 bg-gray-100 text-gray-600 shadow-sm">
                    </div>
                    <div>
                        <label class="block text-sm font-medium text-gray-700">Room No</label>
                        <input type="text" value="{{ optional($user->studentProfile)->room_number ?? 'N/A' }}" readonly 
                            class="mt-1 block w-full rounded-md border-gray-300 bg-gray-100 text-gray-600 shadow-sm">
                    </div>
                    @endif

                </div>

                <hr class="my-6 border-gray-200">

                <!-- Matrix Category Selection -->
                <div class="grid grid-cols-1 sm:grid-cols-2 gap-6 mb-6">
                    
                    <!-- Category Dropdown -->
                    <div>
                        <label class="block text-sm font-medium text-gray-700">Category Selection <span class="text-red-500">*</span></label>
                        <select id="category-select" name="category_id" required
                            class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500">
                            <option value="">-- Choose Category --</option>
                            @foreach($categories as $category)
                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                            @endforeach
                        </select>
                    </div>

                    <!-- Sub-Category Dropdown (Dynamic) -->
                    <div>
                        <label class="block text-sm font-medium text-gray-700">Sub-Category</label>
                        <select id="sub-category-select" name="sub_category_id"
                            class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500">
                            <option value="">-- Select Category First --</option>
                        </select>
                    </div>

                </div>

                <!-- Location specification -->
                <div class="mb-6">
                    <label class="block text-sm font-medium text-gray-700">Location Specification <span class="text-red-500">*</span></label>
                    <input type="text" name="location" placeholder="For maintenance, kindly specify exact location (e.g., Block A, Near Lab 3)..." required
                        class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500">
                </div>

                <!-- Detail of Issue -->
                <div class="mb-6">
                    <label class="block text-sm font-medium text-gray-700">Detail of Issue <span class="text-red-500">*</span></label>
                    <textarea name="description" rows="4" placeholder="Describe your issue clearly..." required
                        class="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500"></textarea>
                </div>

                <!-- Submit Button -->
                <div class="flex justify-end">
                    <button type="submit" 
                        class="bg-indigo-600 hover:bg-indigo-700 text-white font-semibold py-2.5 px-6 rounded-md shadow transition duration-150 ease-in-out">
                        Submit Complaint Ticket
                    </button>
                </div>

            </form>
        </div>
    </div>

    <!-- AJAX Script to load Sub-Categories dynamically -->
    <script>
        document.getElementById('category-select').addEventListener('change', function () {
            let categoryId = this.value;
            let subCategorySelect = document.getElementById('sub-category-select');
            
            subCategorySelect.innerHTML = '<option value="">Loading options...</option>';

            if (!categoryId) {
                subCategorySelect.innerHTML = '<option value="">-- Select Category First --</option>';
                return;
            }

            fetch(`/api/sub-categories/${categoryId}`)
                .then(response => response.json())
                .then(data => {
                    subCategorySelect.innerHTML = '<option value="">-- Select Sub-Category --</option>';
                    if (data.length === 0) {
                        subCategorySelect.innerHTML = '<option value="">No sub-categories available</option>';
                    } else {
                        data.forEach(sub => {
                            let option = document.createElement('option');
                            option.value = sub.id;
                            option.textContent = sub.name;
                            subCategorySelect.appendChild(option);
                        });
                    }
                })
                .catch(error => {
                    console.error('Error fetching subcategories:', error);
                    subCategorySelect.innerHTML = '<option value="">Error loading sub-categories</option>';
                });
        });
    </script>
</x-app-layout>